name: gracecottage
description: GraceCottage - Flutter + Firebase agribusiness app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0

  # State management
  provider: ^6.0.5

  # Image picking
  image_picker: ^1.1.2

  path_provider: ^2.1.1
  # UI helpers
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
