// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWZwhnZzSkcVTMEABFoKpd7OdcMkq3Qn8',
    appId: '1:942487696229:web:7f1a6dabf58722629be78c',
    messagingSenderId: '942487696229',
    projectId: 'gracecottage',
    authDomain: 'gracecottage.firebaseapp.com',
    storageBucket: 'gracecottage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw2vKtOisJULpJdiG9yzNifF1vHREIPWo',
    appId: '1:942487696229:android:6352f602fce16e649be78c',
    messagingSenderId: '942487696229',
    projectId: 'gracecottage',
    storageBucket: 'gracecottage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15yieB1577c3P7Bx1Yv5nkI1L8hCPLIs',
    appId: '1:942487696229:ios:196a26f0d69f68449be78c',
    messagingSenderId: '942487696229',
    projectId: 'gracecottage',
    storageBucket: 'gracecottage.firebasestorage.app',
    iosBundleId: 'com.example.graceCottage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA15yieB1577c3P7Bx1Yv5nkI1L8hCPLIs',
    appId: '1:942487696229:ios:196a26f0d69f68449be78c',
    messagingSenderId: '942487696229',
    projectId: 'gracecottage',
    storageBucket: 'gracecottage.firebasestorage.app',
    iosBundleId: 'com.example.graceCottage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWZwhnZzSkcVTMEABFoKpd7OdcMkq3Qn8',
    appId: '1:942487696229:web:7d61b8887d7510479be78c',
    messagingSenderId: '942487696229',
    projectId: 'gracecottage',
    authDomain: 'gracecottage.firebaseapp.com',
    storageBucket: 'gracecottage.firebasestorage.app',
  );
}